### ISSUE TITLE
what version of cudnn did you used?

### ISSUE THREAD

**Issue by luoyixin2019** [fidler-lab/polyrnn-pp-pytorch#37]
thanks for your contribution.
I would like to ask you some question.
Firstly, what version of cudnn did you used?
Secondly, I cant run you Tool code in my computer. it show that there are some questions at CUDNN.
the error show that:

[2020-01-10 20:31:07,787] ERROR in app: Exception on /api/annotation_and_ggnn [POST]
Traceback (most recent call last):
  File "/home/lyx/code/PolygonRNN/polyrnn-pp-pytorch/env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyx/code/PolygonRNN/polyrnn-pp-pytorch/env/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lyx/code/PolygonRNN/polyrnn-pp-pytorch/env/local/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyx/code/PolygonRNN/polyrnn-pp-pytorch/env/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lyx/code/PolygonRNN/polyrnn-pp-pytorch/env/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyx/code/PolygonRNN/polyrnn-pp-pytorch/env/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "Tool/tool.py", line 153, in generate_annotation_and_ggnn
    pred_annotation = tool.annotation(instance, run_ggnn=True)
  File "Tool/tool.py", line 66, in annotation
    run_ggnn=run_ggnn
  File "/home/lyx/code/PolygonRNN/polyrnn-pp-pytorch/env/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lyx/code/PolygonRNN/polyrnn-pp-pytorch/code/Models/Poly/polyrnnpp.py", line 121, in forward
    concat_feats, feats = self.encoder(x)
  File "/home/lyx/code/PolygonRNN/polyrnn-pp-pytorch/env/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lyx/code/PolygonRNN/polyrnn-pp-pytorch/code/Models/Encoder/resnet_skip.py", line 73, in forward
    fc_f, conv1_f, layer1_f, layer2_f, layer3_f, layer4_f = self.resnet(x)
  File "/home/lyx/code/PolygonRNN/polyrnn-pp-pytorch/env/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lyx/code/PolygonRNN/polyrnn-pp-pytorch/code/Models/Encoder/resnet.py", line 89, in forward
    x = self.conv1(x)
  File "/home/lyx/code/PolygonRNN/polyrnn-pp-pytorch/env/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lyx/code/PolygonRNN/polyrnn-pp-pytorch/env/local/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

I strictly used the same version with you:Ubuntu 16.04, Python 2.7.12, Pytorch 0.4.0, CUDA 9.0,TITAN XP.
So can you answer my questions?
I am hope for your reply.

**Comment by luoyixin2019** [comment]
I solve this problem add "CUDA_VISIBLE_DEVICES=7"(7 is point to the TITAN Xp), before the "python Tool/tool.py........".
